package org.cf.card.model;

// Generated Sep 10, 2015 2:25:00 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.AUTO;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Embryo generated by hbm2java
 */
@Entity
@Table(name = "embryo")
public class Embryo implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = AUTO)
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "injection", columnDefinition = "int default 0")
    private int injection;

    @JsonIgnore
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "embryo", cascade = CascadeType.ALL)
    private Set<EmbryoCode> embryoCodes = new HashSet<EmbryoCode>(0);

    public Embryo() {
    }

    public Embryo(Long id, int injection) {
		this.id = id;
		this.injection = injection;
	}

	public Embryo(int injection, Set<EmbryoCode> embryoCodes) {
        this.injection = injection;
        this.embryoCodes = embryoCodes;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }


	public int getInjection() {
		return injection;
	}

	public void setInjection(int injection) {
		this.injection = injection;
	}

	public Set<EmbryoCode> getEmbryoCodes() {
		return embryoCodes;
	}

	public void setEmbryoCodes(Set<EmbryoCode> embryoCodes) {
		this.embryoCodes = embryoCodes;
	}



}
