package org.cf.card.model;

// Generated Sep 10, 2015 2:25:00 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.AUTO;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * SemenData generated by hbm2java
 */
@Entity
@Table(name = "semen_data")
public class SemenData implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = AUTO)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "semen_id")
	private Semen semen;

	@Column(name = "volume", columnDefinition  ="float default 0.0")
	private float volume;

	@Column(name = "density", columnDefinition  ="float default 0.0")
	private float density;

	@Column(name = "motilityA", columnDefinition  ="int default 0")
	private int motilityA;

	@Column(name = "motilityB", columnDefinition  ="int default 0")
	private int motilityB;

	@Column(name = "motilityC", columnDefinition  ="int default 0")
	private int motilityC;

	@Column(name = "motilityD", columnDefinition  ="int default 0")
	private int motilityD;

	@Column(name = "round_cell", columnDefinition  ="int default 0")
	private int roundCell;

	@Column(name = "morphology", columnDefinition  ="float default 0.0")
	private float morphology;

	@Column(name = "_type", nullable = false, length = 2)
	private int type;

	public SemenData() {
	}

	public SemenData(Long id, Semen semen, int volume, float density, int motilityA, int motilityB,
			int motilityC, int motilityD, int roundCell, float morphology, int type) {
		this.id = id;
		this.semen = semen;
		this.volume = volume;
		this.density = density;
		this.motilityA = motilityA;
		this.motilityB = motilityB;
		this.motilityC = motilityC;
		this.motilityD = motilityD;
		this.roundCell = roundCell;
		this.morphology = morphology;
		this.type = type;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Semen getSemen() {
		return this.semen;
	}

	public void setSemen(Semen semen) {
		this.semen = semen;
	}

	public float getVolume() {
		return this.volume;
	}

	public void setVolume(float volume) {
		this.volume = volume;
	}

	public float getDensity() {
		return density;
	}

	public void setDensity(float density) {
		this.density = density;
	}

	public int getMotilityA() {
		return motilityA;
	}

	public void setMotilityA(int motilityA) {
		this.motilityA = motilityA;
	}

	public int getMotilityB() {
		return motilityB;
	}

	public void setMotilityB(int motilityB) {
		this.motilityB = motilityB;
	}

	public int getMotilityC() {
		return motilityC;
	}

	public void setMotilityC(int motilityC) {
		this.motilityC = motilityC;
	}

	public int getMotilityD() {
		return motilityD;
	}

	public void setMotilityD(int motilityD) {
		this.motilityD = motilityD;
	}

	public int getRoundCell() {
		return this.roundCell;
	}

	public void setRoundCell(int roundCell) {
		this.roundCell = roundCell;
	}

	public float getMorphology() {
		return morphology;
	}

	public void setMorphology(float morphology) {
		this.morphology = morphology;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}
}
