/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.cf.card.ui.service.printing.templates;

import org.cf.card.ui.model.UIClient;
import org.cf.card.ui.model.UIPrintClient;
import org.cf.card.ui.service.UIClipartService;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 * @author Dell
 */
public class braceletTemplate extends JPanel {

    private final UIClipartService clipartService = new UIClipartService();

    /**
     * Creates new form braceletTemplate
     */




    public braceletTemplate(UIPrintClient client) {
    	setMaximumSize(new Dimension(326, 141));
    	setMinimumSize(new Dimension(326, 141));
    	setFont(new Font("Open Sans", Font.PLAIN, 11));
        initComponents();

        BufferedImage img = null;
        try {
            img = ImageIO.read(new File(clipartService.getImage(client.getMainClient().getCouple().getId())));
        } catch (IOException e) {
            e.printStackTrace();

        }

        Image dimg = img.getScaledInstance(121, 115,
                Image.SCALE_SMOOTH);

        ImageIcon imageIcon = new ImageIcon(dimg);
        designLabel.setIcon(imageIcon);

        UIClient uiClient = new UIClient(client.getMainClient());

        surnameLabel.setText(uiClient.getClient().getSurname().toUpperCase());

        try {
            otherNamesLabel.setText(uiClient.getClient().getFirstName() + " " + uiClient.getClient().getMiddleName());
        }catch(StringIndexOutOfBoundsException e){
            otherNamesLabel.setText(uiClient.getClient().getFirstName());
        }
            dOBLabel.setText(new SimpleDateFormat("dd/MM/yyyy").format(uiClient.getClient().getdOB()));
        ageLabel.setText(uiClient.getAge());
        codeLabel.setText("" + client.getMainClientTreatmentCode().getCode());
     /*   secondAlphanumericCharacter.setText("" + client.getMainClientTreatmentCode().getCode().charAt(1));
        ThirdAlphanumericCharacter.setText("" + client.getMainClientTreatmentCode().getCode().charAt(2));*/

//
//        ThirdAlphanumericCharacter.setVisible(false);
//        ageLabel.setVisible(false);
//        dOBLabel.setVisible(false);
//        designLabel.setVisible(false);
//        firstAlphanumericCharacter.setVisible(false);
//        jLabel3.setVisible(false);
//        jLabel4.setVisible(false);
//        jLabel5.setVisible(false);
//        jLabel8.setVisible(false);
//        otherNamesLabel.setVisible(false);
//        secondAlphanumericCharacter.setVisible(false);
//        surnameLabel.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        surnameLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        otherNamesLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dOBLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codeLabel = new javax.swing.JLabel();
        designLabel = new javax.swing.JLabel();
        designLabel.setFont(new Font("Open Sans", Font.PLAIN, 11));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new Dimension(326, 141));

        surnameLabel.setBackground(new java.awt.Color(255, 255, 255));
        surnameLabel.setFont(new Font("Open Sans", Font.BOLD, 15)); // NOI18N
        surnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        surnameLabel.setText("KOLOROV");
        surnameLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(204, 204, 204)));
        surnameLabel.setIconTextGap(6);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new Font("Open Sans", Font.ITALIC, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Surname");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new Font("Open Sans", Font.ITALIC, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Other Names");

        otherNamesLabel.setBackground(new java.awt.Color(255, 255, 255));
        otherNamesLabel.setFont(new Font("Open Sans", Font.BOLD | Font.ITALIC, 15)); // NOI18N
        otherNamesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otherNamesLabel.setText("Freeman R.");
        otherNamesLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(204, 204, 204)));
        otherNamesLabel.setIconTextGap(6);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new Font("Open Sans", Font.ITALIC, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("D.O.B.");

        dOBLabel.setBackground(new java.awt.Color(255, 255, 255));
        dOBLabel.setFont(new Font("Open Sans", Font.PLAIN, 15)); // NOI18N
        dOBLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dOBLabel.setText("22/01/1994");
        dOBLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(204, 204, 204)));
        dOBLabel.setIconTextGap(6);

        ageLabel.setBackground(new java.awt.Color(255, 255, 255));
        ageLabel.setFont(new Font("Open Sans", Font.PLAIN, 15)); // NOI18N
        ageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ageLabel.setText("20");
        ageLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(204, 204, 204)));
        ageLabel.setIconTextGap(6);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new Font("Open Sans", Font.ITALIC, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Age");

        codeLabel.setBackground(new java.awt.Color(255, 255, 255));
        codeLabel.setFont(new Font("Open Sans", Font.BOLD, 18)); // NOI18N
        codeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codeLabel.setText("G");
        codeLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        designLabel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(designLabel, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
        					.addGap(0)
        					.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        						.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(otherNamesLabel, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE)
        							.addGap(3))
        						.addComponent(surnameLabel, GroupLayout.PREFERRED_SIZE, 197, GroupLayout.PREFERRED_SIZE)
        						.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(codeLabel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(dOBLabel, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(ageLabel, GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
        							.addGap(3)))
        					.addGap(1))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(1)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(surnameLabel, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        					.addGap(0)
        					.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
        					.addGap(0)
        					.addComponent(otherNamesLabel, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        					.addGap(0)
        					.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(dOBLabel, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        						.addComponent(ageLabel, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
        					.addGap(5)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(codeLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addContainerGap())
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(designLabel, GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        					.addGap(2))))
        );
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel dOBLabel;
    private javax.swing.JLabel designLabel;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel otherNamesLabel;
    private javax.swing.JLabel surnameLabel;
    // End of variables declaration//GEN-END:variables
}
